name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - sklearn
  - seaborn
  - matplotlib
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
