name: example-environment
channels:
  - conda
dependencies:
  - python
  - numpy
  - scikit-learn
  - seaborn
  - matplotlib
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
